### ISSUE TITLE
Suggestion: My confusion over update() v create() and when to use save()

### ISSUE THREAD

**Issue by sunscreem** [laravel/docs#2389]
This might be me being really dumb but in the [Basic Updates](https://laravel.com/docs/5.2/eloquent#basic-updates) section about Eloquent, I was confused over when I need to use save and when just update would be fine.

**Comment by henriquebremenkanp** [comment]
I think this is worth taking a look too... Just read all of it and these are my impressions:

#### Regarding mass assignment: 
- [Basic Inserts](https://laravel.com/docs/5.2/eloquent#basic-inserts) and [Basic Updates](https://laravel.com/docs/5.2/eloquent#basic-updates) should be explained after [Mass Assignment](https://laravel.com/docs/5.2/eloquent#mass-assignment) as they will both fail if `$fillable` isn't set.
- [This example](https://github.com/laravel/docs/blame/5.2/eloquent.md#L297-L303) will not respect fillable properties as it is the QueryBuilder object, different from any other sample in this page. Maybe it should be better to say you can use `Flight::where()` meaning the same as `DB::table('flights')->where()`and receive a QueryBuilder instance. Specially now on 5.3 as we get collections on both. This way we can let this update() documentation be only on [Queries](https://laravel.com/docs/5.2/queries#updates), where it seems to fit better.
- [Other Creation Methods](https://laravel.com/docs/5.2/eloquent#mass-assignment) feels displaced under "Mass Assignment". Maybe it should be nicer if moved to the end of [Basic Inserts](https://laravel.com/docs/5.2/eloquent#basic-inserts).

#### Regarding updates
There's one case I saw two completely different people mistaking and docs doesn't address it.
One being documented [here in this japanese article.](http://qiita.com/gomaaa/items/91e5cbd319279a2db6ec)
It says to be careful when using `save()` or `update()` on your model because unlike `update()`, `save()` won't update your `updated_at` timestamp if the input is the same as the original data. 
I think it's worth mentioning in the docs that `save()` won't perform any query if the data haven't changed. Current documentation about this has [a good example](https://github.com/laravel/docs/blame/5.2/eloquent.md#L289) but it feels like a trap many people fall into as they change `'New Flight Name'` for `$request->name`;

Different from the `update()` mentioned on the second point regarding mass assignment above, this `update()` respects `$fillable`.

#### Mention to fill() method.

We know many people will just pass data from `$request->all()` to update a model as we don't always assign every property one by one. The docs encourages us to do:
```php
App\Flight::find(1)->update($request->all());
```
Which is fine, but now it comes to my personal opinion...

I think it might be easier for people to understand if we make a mention to populating data with the fill method and save it after as `fill` refers to `$fillable` and has no chance to be mistaken with the QueryBuilder's update method.
```php
App\Flight::find(1)->fill($request->all())->save();
```

```php
// I can imagine people getting confused and changing
App\Flight::find(1)->update($data);
// To
App\Flight::whereId(1)->update($data);
// Just because it works.
```

If I knew nothing about Laravel and read `fill()->save()` it may give me a clue that fields not being filled are assigned to be fillable somewhere. It should be better if docs encourages this usage.

I can submit a PR if @taylorotwell thinks some of these suggestions can be helpful.

**Comment by carusogabriel** [comment]
@sunscreem Can you please close this issue due inactivity?
