### ISSUE TITLE
No observer documentation in 5.2

### ISSUE THREAD

**Issue by TheDeadCode** [laravel/docs#2539]
Hello! Some company policies may require documentation of a feature prior to usage. We'd love you forever if you could document it =)

**Comment by lagbox** [comment]
It is documented in 5.0 and hasn't been removed.
The docs do not cover everything and they wont.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
