### ISSUE TITLE
Custom Facades

### ISSUE THREAD

**Issue by clarkeash** [laravel/docs#2574]
I noticed there is no longer docs on creating custom facades (I think 4.2 was the last to have it) would you be open to adding this? I'd be happy to create a PR.

**Comment by lagbox** [comment]
https://laravel.com/docs/5.3/facades#how-facades-work
That section illustrates how they work, does that need to be expanded with different wording perhaps?

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
