### ISSUE TITLE
Document how to use a different model for authentication

### ISSUE THREAD

**Issue by HipsterJazzbo** [laravel/docs#2595]
This question has come up a few times recently. We should add a bit of documentation to show how to extend `Illuminate\Foundation\Auth\User` and change the model in `auth.php` config.

I'm happy to write up a PR if @taylorotwell can chime in about whereabouts he'd like this documentation to sit.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
