### ISSUE TITLE
Broadcast toOthers() needs InteractsWithSockets trait

### ISSUE THREAD

**Issue by AdamEsterle** [laravel/docs#2647]
There is no mention of the need for the InteractsWithSockets trait on your event when you want to use the toOthers() method.

Otherwise,

```
public function toOthers()
    {
        if (method_exists($this->event, 'dontBroadcastToCurrentUser')) {
            $this->event->dontBroadcastToCurrentUser();
        }

        return $this;
    }
```

the "dontBroadcastToCurrentUser" method will not exist and never get run

**Comment by AdamEsterle** [comment]
Looks like that trait is automatically added when going make:event

**Comment by troygilbert** [comment]
It may be automatically added with `make:event`, but good docs should not depend on that. The `toOthers()` section *must* make mention of this, or otherwise *everyone* will waste hours debugging everything on the network side of things trying to figure out why it's not doing what would you expect. The example code doesn't even show it being used.

**Comment by AdamEsterle** [comment]
OK I will re-open it to see if anyone else deems it important

**Comment by Yiin-** [comment]
Please include this, it's definitely too important not to mention.

**Comment by laurencei** [comment]
I've submitted a PR to solve this problem. It is up to Taylor if it gets pulled in.
