### ISSUE TITLE
5.3 from 5.2 guide is not complete

### ISSUE THREAD

**Issue by sajin577** [laravel/docs#2657]
1. It does not mentions change of route file
2. RouteServiceProvider: 

No mention about new function mapApiRoutes.

This is what I detected so far. Please keep updating this thread.

**Comment by bobbybouwmann** [comment]
Send in a PR if you have any changes for the upgrade guide ;)

**Comment by lagbox** [comment]
If you are upgrading than your RouteServiceProvider won't have that method (because you have the one you got when you installed laravel/laravel, when ever that was). This doesn't break your app. Since that Service Provider is in your app, you can leave it as it is or, update it to match the default one that comes with the project. Concern 1 and 2 are completely optional changes.

**Comment by laurencei** [comment]
I'm closing this ticket. As mentioned - the changes above are optional changes.

All upgrade guides from 5.4 onwards make mention of "misc" changes that have occured in `laravel/laravel` and you are free to copy them across to your project if it suits you.
