### ISSUE TITLE
https://laravel.com/docs/5.3/testing seems to be missing a bunch of content as compared to 5.2

### ISSUE THREAD

**Issue by edgreenberg** [laravel/docs#2720]
Not sure if this is by design, but I don't think I'd have been able to make progress without the info in the 5.2 and 5.1 page.

**Comment by DCzajkowski** [comment]
The docs **are there**, but are not as intuitive to find. The 'testing' docs have been split into 4 sub-pages. They are accessible via the sidebar:

---

### Testing
[Getting Started](https://laravel.com/docs/5.3/testing)
[Application Testing](https://laravel.com/docs/5.3/application-testing)
[Database](https://laravel.com/docs/5.3/database-testing)
[Mocking](https://laravel.com/docs/5.3/mocking)

**Comment by laurencei** [comment]
I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
