### ISSUE TITLE
Is there still support for specifiying the identifier of foreign keys?

### ISSUE THREAD

**Issue by kerrinhardy** [laravel/docs#2768]
Example:  $table->foreign('foreign_column', 'fk_name')->references('id')->on('foreign_table');

There is no mention of this in the docs and the foreign key name seems to be ignored in 5.3
https://laravel.com/docs/5.3/migrations#foreign-key-constraints

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
