### ISSUE TITLE
Document raw SQL bindings

### ISSUE THREAD

**Issue by seanmangar** [laravel/docs#2791]
I've noticed that the raw expressions section in the Laravel documentation does not mention how to perform raw SQL queries and bind parameters. There are articles online about how to do this. For e.g: `http://fideloper.com/laravel-raw-queries` . 

Do you guys think this should be included?

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and the Database section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
