### ISSUE TITLE
Authorization with @can in templates without a Model

### ISSUE THREAD

**Issue by pjotrsavitski** [laravel/docs#2804]
There is an issue with usage of @can('create', Post::class) within templates documented here: https://laravel.com/docs/5.3/authorization#via-blade-templates

This code will not work:

    @can('create', Post::class)
        
    @endcan

The issue is that **Post::class** will be understood as **Post** not **App\Post**. This way, it would not be possible to check the permission from the correct Policy.

This code works just fine (please note the explicit use of class):

    @can('create', 'App\Post')
        
    @endcan

The class has been exposed using **aliases** from the **config/app.php**.

This is either a bug of the implementation, misleading documentation or some special step with correct class exposure is missing.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
