### ISSUE TITLE
5.2 to 5.3 error in production

### ISSUE THREAD

**Issue by rsands2801** [laravel/docs#2833]
The documentation doesnt mention the composer post install and post update now have

"Illuminate\\Foundation\\ComposerScripts::postUpdate",

These scripts are critical to a production environment or it will break everything as bootstrap/cache isn't cleared before it fails with class methods not matching e.g. Boot()

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
