### ISSUE TITLE
Document the name of the Postgres driver

### ISSUE THREAD

**Issue by kevinburke** [laravel/docs#2855]
I'm trying to use Eloquent with Postgres. I tried this:

```php
        // database
        'db' => [
            'driver' => 'postgresql',
            'host' => 'localhost',
            'database' => 'commander',
            'username' => 'commander',
            'password' => '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
```

and got ` "message": "Unsupported driver [postgresql]",`. I then tried googling "laravel postgres", "laravel supported drivers", "laravel eloquent postgres driver". The best result I got was this page, https://laravel.com/docs/5.3/database, which mentions Postgres support but does not mention the key you need to use Postgresql as a database driver. I eventually figured out it's "pgsql", not "postgres" or "postgresql", but I had to search StackOverflow to find the right answer here.

It would be nice if this was documented on Laravel's website (or made easier to find).

**Comment by laurencei** [comment]
I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written. The driver names are now also included in the `laravel/laravel` default config as well.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
