### ISSUE TITLE
Document that you don't need to list fields in a ORM model

### ISSUE THREAD

**Issue by kevinburke** [laravel/docs#2858]
Reading https://laravel.com/docs/5.3/eloquent, I was fairly confused that you started referring to the Flight's `name`, and `legs`, without ever defining those in the model file. I guess it's fine to just set properties on a thing, without defining them first? I'm used to having to list all of the fields in a table and their types.

It would be nice to have a short note that you don't need to define the fields or their types in the ORM model.

**Comment by laurencei** [comment]
I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
