### ISSUE TITLE
JSON Queries

### ISSUE THREAD

**Issue by nkconnor** [laravel/docs#2946]
Laravel uses the -> JSON selector syntax in the MySQL Grammar

```
mysql> SELECT c, c->"$.id", g
     > FROM jemp
     > WHERE c->"$.id" > 1
     > ORDER BY c->"$.name";
+-------------------------------+-----------+------+
| c                             | c->"$.id" | g    |
+-------------------------------+-----------+------+
| {"id": "3", "name": "Barney"} | "3"       |    3 |
| {"id": "4", "name": "Betty"}  | "4"       |    4 |
| {"id": "2", "name": "Wilma"}  | "2"       |    2 |
+-------------------------------+-----------+------+
3 rows in set (0.00 sec)
```

However, it does not add `JSON_UNQUOTE` or any method to remove the double quotes from the result set. Since the queries are evaluated via the database we need to include the extra "'s in our search values, e.g. `::where('context->team->name', 'LIKE', '%angeles"')`

Should the docs be updated to make this clear? Or is adding `JSON_UNQUOTE` feasible?

**Comment by laurencei** [comment]
@sisve - your an expert at this type of stuff. What are your thoughts?

**Comment by sisve** [comment]
My bitterness is mostly focused around release management and stability, and this issue seems to be focused on documentation ... but that won't stop me! ;)

I understand the idea behind the quotes, there's no way for me to differ between the string value `"3"` and the numeric value `3` without them. Perhaps if mysqlnd was used with type information; but can mysql really provide any reliable type information when every row can have a custom json format with a unique type?

Using JSON_UNQUOTE in this case would probably work, but there are also problems with it. It not only removes the quotes, it unquotes the entire value. If we've stored the value `'Hello\nworld!'`, then we expect that same string value back when querying, and not a string with a real newline character in it. I guess this is the reason behind the decision, on a framework level, to not use JSON_UNQUOTE.

Mysql has the `column->>path` syntax which is equal to `JSON_UNQUOTE(column->path)`. (Postgresql also have this syntax.) This sounds like the obvious solution for this specific question; `->where('context->>team->>name', 'LIKE', '%angeles')`, but I'm not sure if Laravel supports this. I haven't tried it myself when writing this comment.

But, in the end, this is a issue filed against the documentation repository. So, in the context of documentation, it makes sense to add a hint about this in the documentation, perhaps under the [JSON Where Clauses](https://laravel.com/docs/5.6/queries#json-where-clauses). There are already some examples there that aren't using JSON_UNQUOTE, so there's a high probability that we would have to explain when it would be needed, and when it isn't, and that sounds like a dark dark area to explain in simple terms...

**Comment by laurencei** [comment]
> There are already some examples there that aren't using JSON_UNQUOTE, so there's a high probability that we would have to explain when it would be needed, and when it isn't, and that sounds like a dark dark area to explain in simple terms...

Yeah... I think it's getting beyond the scope of Eloquent, and more into the SQL side of things.

I'm going to close this for now. No one else has raised the issue in over a year, so I think it's an edge case for now.

If anyone has a good clean way to document this without getting too technical, please feel free to submit a PR, or open a new ticket with more details.

Thanks everyone.
