### ISSUE TITLE
redirectTo property and method discussed in Docs

### ISSUE THREAD

**Issue by nakie** [laravel/docs#2949]
https://laravel.com/docs/5.3/authentication#included-authenticating

discusses overriding the redirectTo Property with a function of the same name for dynamic generation of redirectTo Route/URL. I wasn't able to get this to work and started researching its use.    I have only found reference to redirectPath() and don't see a redirectTo() mentioned anywhere else.  

is this simply a typo in the docs or am I missing something?

**Comment by vfsoraki** [comment]
I asked the same question.

http://stackoverflow.com/questions/41506102/laravel-redirect-after-login

Seems like docs were wrong, I created a pull request.

**Comment by nakie** [comment]
I understand now.  I was missing that the redirectTo function was introduced in 5.3.29.   

After reviewing vfsoraki's previous PR https://github.com/laravel/docs/pull/2950 and the Change logs https://github.com/laravel/framework/blob/5.3/CHANGELOG-5.3.md

I have created another PR https://github.com/laravel/docs/pull/2956 that will hopefully eliminate any confusion for others.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
