### ISSUE TITLE
Redis 'client' key no longer appears to be used

### ISSUE THREAD

**Issue by ikari7789** [laravel/docs#3003]
In the docs for Redis, it mentions a "client" key in the configuration array, but it doesn't seem to be used anywhere and isn't included in the default configuration.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
