### ISSUE TITLE
[Discussion] The default `npm run watch` command doesn't watch properly on Vagrant/VirtualBox

### ISSUE THREAD

**Issue by monomichael** [laravel/docs#3072]
This is not really an issue for either laravel or webpack, but I'm thinking if we should warn people in the documentation that if they are using **Vagrant / VirtualBox**, they should add `--watch-poll` to the `npm run watch` command.

According to [this issue](https://www.virtualbox.org/ticket/10660), files updated in shared folders won't trigger inotify, and therefore `npm run watch` won't watch files properly if they run the command in the guest system but change files on the host machine.

We can either change the default command to include the `--watch-poll` flag or update the documentation. Thoughts?

**Comment by Aidanwang0309** [comment]
I vote for the documentation change. Thanks for the solution though.

**Comment by laurencei** [comment]
Hi @monomichael - if this is still an issue on the recent versions of Vagrant / VirtualBox, please feel free to submit a PR with the documentation change and Taylor can review it.

**Comment by hellvesper** [comment]
I guess `--watch-poll` still doesn't work with vagrant/virtualbox (Homestead) + NFS

**Comment by faustnord** [comment]
Guys, I found the perfect solution to this problem in [this blog](https://blog.codecentric.de/en/2017/08/fix-webpack-watch-virtualbox/). At the end of the article, after manually solving the problem, the author cites a [link to the library](https://github.com/mhallin/vagrant-notify-forwarder) containing the Vagrant plugin, which does everything automatically.
Why would anyone not turn on this plugin officially, because this method makes the "npm run watch" work for VirualBox immediately after installation.
