### ISSUE TITLE
Documentation for ManyToMany  syncWithoutDetaching()

### ISSUE THREAD

**Issue by thepeels** [laravel/docs#3082]
It seems that syncWithoutDetaching no longer exists and that it is now sync(array(),false)

**Comment by morloderex** [comment]
It does exist! 
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L70

**Comment by thepeels** [comment]
That was my point, the documents show it, but using it, gets a BadMethodCallException - Call to undefined method. Using "sync(array(),false)" works, but it took me a long time to find out. I was hoping someone might update the docs.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
