### ISSUE TITLE
Document $this->app->extend

### ISSUE THREAD

**Issue by joshbrw** [laravel/docs#3130]
I'm still not exactly sure what it does, but it seemed to fulfill my purpose of changing out the instance of the migration command using the following code:

```
$this->app->extend('command.migrate', function ($currentInstance, $app) {
            return new MigrateCommand($app['migrator']);
        });
```

**Comment by laurencei** [comment]
I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
