### ISSUE TITLE
Running dusk tests with phpunit

### ISSUE THREAD

**Issue by masterwto** [laravel/docs#3140]
After modifing the phpunit.xml file, test cases extending the DuskTestCse class can be run together with those entending TestCase, just run the phpunit command. However, artisan:dusk command just tests the Browser folder.

**Comment by enderandpeter** [comment]
It might help to create/modify the `phpunit.dusk.xml` file to customize what happens for `php artisan dusk`.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
