### ISSUE TITLE
trans to __ change not mentioned in release notes

### ISSUE THREAD

**Issue by kevinfoley** [laravel/docs#3144]
The documentation for Localization for Laravel 5.3 indicates that language lines are retrieved with the 'trans' helper function:  https://laravel.com/docs/5.3/localization

The documentation for Localization for Laravel 5.4 indicates that language lines are retrieved with the '__' helper function: https://laravel.com/docs/5.4/localization

This change is not mentioned in the Laravel 5.4 Release Notes ( https://laravel.com/docs/5.4/releases ) or Upgrade Guide ( https://laravel.com/docs/5.4/upgrade )

**Comment by paulofreitas** [comment]
Actually the `trans` helper is still supported. 😃 

The documentation was changed to use the `__` helper for simplification since you could use it for retrieving language strings from both legacy language files and the new JSON-based language files. 
So instead of mixing the usage of `trans` and `__` helpers in the documentation it's better to pick only the smartest one that can be used interchangeably. 👍 

But yeah, this new feature would be nice to be mentioned in the release notes (changing the upgrade guide is not required since the `trans` helper is still supported). I'll provide a PR to mention the new JSON-based language files in the release notes soon. :wink:

**Comment by laurencei** [comment]
@themsaid - as the localization expert - do we need to change anything here, or can both functions be used?

**Comment by themsaid** [comment]
`__()` will look for lines inside the JSON files, if nothing found it'll look into the array files so basically it'll work same as `trans()` if not JSON keys were found.

So no need to apply any changes imo.
