### ISSUE TITLE
Mandrill mail driver removed in 5.4 but not mentioned in upgrade guide

### ISSUE THREAD

**Issue by WellsMediaGroup** [laravel/docs#3220]
It appears that MAIL_DRIVER=mandrill is no longer a valid option with Laravel 5.4.  It was removed from the docs in 5.3, but still functioned.

It should probably be mentioned in the upgrade guide for 5.4 that smtp should be used in place of mandrill.

**Comment by paulofreitas** [comment]
It's still valid and supported, look here at the `Illuminate\Mail\TransportManager`: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Mail/TransportManager.php#L129

It only asks for a secret API key, though.

This was removed since 70870f2c02b19491803cfdc64c3e1e9d43f80fa8 when Taylor was improving the documentation for 5.4 release.

Why this was removed I don't know either, so let's wait anyone from the team to guide us if we can add it back. 😄

**Comment by joshuaziering** [comment]
Do I need to change my config or what? No emails are sending for me suddenly since moving to 5.4

**Comment by ChrisThompsonTLDR** [comment]
MAIL_DRIVER=smtp should do the trick for you.

**Comment by daftspunk** [comment]
Mandrill pulled a dick move and forced everyone to purchase MailChimp subscriptions. They are dead to me. I can only assume this is why it was removed.

**Comment by laurencei** [comment]
I'm going to close this ticket.

Mandrill was specifically removed by Taylor in the docs for "reasons".

However the TransportManager still has the driver available, so it should not affect anyone upgrading.

I would suggest looking into alternative options as others have suggested for other open source partners.
