### ISSUE TITLE
Validation: Adding After Hooks To Form Requests — needs to be clarified

### ISSUE THREAD

**Issue by matrunchyk** [laravel/docs#3268]
[Here](https://github.com/laravel/docs/blob/5.4/validation.md#adding-after-hooks-to-form-requests) is stated that

> This method receives the fully constructed validator, allowing you to call any of its methods **before** the validation rules are actually evaluated

Shouldn't it be "after" instead of "before"? Or it means before previous rules were evaluated but before validation FAILs/PASSes?

Thanks.

**Comment by lagbox** [comment]
It is correct how it is.
`withValidator` gets the validator instance before `passes` is called on the instance. `passes` is what evaluates the rules and calls any "after" hooks. 
In regards to the example in that section, since `passes` calls any "after" hooks you would need to register any "after" hooks before the rules are actually evaluated, which is why it uses `withValidator`.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Validation/Validator.php#L242

**Comment by matrunchyk** [comment]
@lagbox yeah, that's how I suspected how it works. Thanks!
