### ISSUE TITLE
Lost documentation for route prefix constraint for >= 5.1

### ISSUE THREAD

**Issue by samgavinio** [laravel/docs#3413]
In the [5.0 docs](https://github.com/laravel/docs/blob/5.0/routing.md#registering-a-url-parameter-in-a-route-prefix) it is documented that you can define parameter constraints for the named parameters in your prefix by passing in a `where` key to Route::group() like so

```
Route::group([
	'prefix' => 'accounts/{account_id}',
	'where' => ['account_id' => '[0-9]+'],
], function() {

	// Define Routes Here
});
```

The doc for this seems to have been removed in https://github.com/laravel/docs/commit/8c28a8b537fb9b926099fc92db85a8a7d4a4bc1b#diff-ce107015c43d323e34bbf68cbc83e623L240 for versions >= 5.1 but the functionality seems to still exist at least in 5.2.

Is this just a documentation issue or is there real intent to remove this functionality?

**Comment by decadence** [comment]
There are many issues where something is lost in new version of docs but is still available in source code.
Often it's intentional but sometimes it's not. Only way to find out it is PR to this repository.

See:
https://github.com/laravel/docs/issues/3191
https://github.com/laravel/docs/pull/3293

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
