### ISSUE TITLE
Localisation says __ helper takes file name and key but then doesn't reflect this in example.

### ISSUE THREAD

**Issue by StyxOfDynamite** [laravel/docs#3453]
Retrieving Translation Strings

>You may retrieve lines from language files using the __ helper function. The __ method accepts the file and key of the translation string as its first argument. For example, let's retrieve the welcome translation string from the resources/lang/messages.php language file:

`echo __('messages.welcome');`

`echo __('I love programming.');`

So which file is the `'I love programming.'` key to be found in ?

https://laravel.com/docs/5.4/localization#retrieving-translation-strings

**Comment by carusogabriel** [comment]
Is coming from the example above: [`Using Translation Strings As Keys`](https://laravel.com/docs/5.5/localization#using-translation-strings-as-keys), saying:
> For applications with heavy translation requirements, defining every string with a "short key" can become quickly confusing when referencing them in your views.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
