### ISSUE TITLE
[5.5] Blade Templates: @@parent - double mark?

### ISSUE THREAD

**Issue by WebDevWaw** [laravel/docs#3632]
# Blade Templates
## Extending A Layout

```
@section('sidebar')
   @@parent
  <p>This is appended to the master sidebar.</p>
 @endsection
```

> In this example, the sidebar section is utilizing the @@parent directive to append (rather than overwriting) content to the layout's sidebar. The @@parent directive will be replaced by the content of the layout when the view is rendered.

--
I tested it as suggested with double mark @ (vide: `@@parent`), but it doesn't work properly.
When I used a single (vide: `@parent`), all worked fine.
I was a little surprised to use double mark directives when the others directives are single. It would be inconsistent.

Maybe I'm wrong, but isn't an important typo in the documentation?
Test on Laravel 5.5 (Widnows)

**Comment by brunogaspar** [comment]
AFAIK that's not a typo. It's actually a feature of Blade to disable whatever you prepend with @ from being compiled. 

I'm this case, the extra @ is so the documentation can be rendered properly, since it's actually being  rendered by Blade. If you check the online example, you don't see it.

Hope it helps.

**Comment by WebDevWaw** [comment]
When I prepend extra @ an @parent directive - my app  returns result: 
````
@parent
This is appended to the master sidebar.
````

When I use single, my app  returns result: 
````
This is the master sidebar.
This is appended to the master sidebar.
````

So which result is correct?

**Comment by brunogaspar** [comment]
You shouldn't prepend, just use `@parent` and that's it.

You're mostlikely reading the documentation here on GitHub, just read the documentation online https://laravel.com/docs/5.5/blade#extending-a-layout which is compiled correcly.

**Comment by WebDevWaw** [comment]
Brunogaspar - Why are the differences between both documents?
https://laravel.com/docs/5.5/blade
https://github.com/laravel/docs/blob/5.5/blade.md

I translate the documentation in my language. It is very important know to me, where do these differences come from? It seemed to me that the GIT version should be the most up to date.

**Comment by brunogaspar** [comment]
This https://github.com/laravel/docs/blob/5.5/blade.md is the raw documentation. GitHub doesn't compile it like on the Laravel Documentation Website.

As i explained before, the `@` before is for that stuff not being rendered, otherwise that piece of code would be rendered.

If you remove the `@@` from it, on the Laravel documentation it would show

```
@section('sidebar')
  <p>This is appended to the master sidebar.</p>
@endsection
```

As you can see, it would render without the `@parent` call.

Therefore, there's no bug or duplication.

Hope it clarifies.

**Comment by WebDevWaw** [comment]
I take a note that the GIT version is parsed and that's why it need double @@. 
OK, it seems understandable. 

But then why other directives not needed prepend? They are also parsed...
**Is it an exception** in the processing of doc?

**Comment by laurencei** [comment]
It seems this confusion has been resolved. If there are any further issues with the documentation itself, please feel free to open a new issue and we'll look into it.
