### ISSUE TITLE
Request: Add Upgrade Guide for 5.1 to 5.5

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/docs#3639]
Since Laravel 5.1 was the previous LTS, it would be nice to see an upgrade guide from LTS to LTS (Something other than, "Just upgrade 5.1 to 5.2, then to 5.3, then to 5.4, then to 5.5").

I currently have a couple of 5.1 projects that I'd like to move up to 5.5, and having a single to-do list would be great.

**Comment by arasmit2453** [comment]
I think this will be to overwhelming to have all the steps in one screen, its better to follow up all the steps one by one

I suggest that you check https://laravelshift.com/ it could save you some time to do the upgrade

**Comment by tylernathanreed** [comment]
@arasmit2453 Perhaps, but a think that a lot of it can be consolidated.

Examples:
* You don't have to say "Upgrade PHP to 5.6, then upgrade it 7.0". You can just say "Upgrade PHP to 7.0".
* You don't have to say "X feature has been deprecated in 5.2, and will be removed in 5.3", you can just say, "X feature has been removed."

Several of the changes could be grouped together for clarity, especially if someone is planning on walking through it. For example, it would be nice to know everything that I need to upgrade, so that I can do it all at once. I don't want to upgrade a couple of things, dive into a different section of the code, and then learn that I still have to upgrade some other things.

**Comment by tylernathanreed** [comment]
If only I had unit tests to run. According to my CEO, that process is "too expensive", as it wastes developer time. *sigh*....

**Comment by arasmit2453** [comment]
I have seen that before and is just matter of explaining him why you should upgrade and not keep waiting on it.

1- Once laravel 5.1 is not supported anymore you might find bugs in the framework that you have to workaround yourself
2- PHP versions are being deprecated and not supported quite fast so in 1 or 2 years you might be facing the issue that you can't run PHP 7.1 easily in the latest Ubuntu installations
3- Laravel comes with very nice new features in new versions so you are missing all of them and probably some of them you have to build yourself and that means more expensive development, for example all the notification improvements, imagine that you want to include that in your app but you can't because you haven't upgraded so that means that you have to fork the package and make it work in Laravel 5.1.

If you have one big software running on laravel just keep it updated once new versions are released we update our core software 2 months after the latest version is released and that has been working perfectly for us. We are always at the latest versions without having to spend insane amount of time on upgrades

**Comment by JaydenJames** [comment]
> If only I had unit tests to run. According to my CEO, that process is "too expensive", as it wastes developer time. sigh....

Man, sorry to hear that... it must be painful not just to upgrade the framework but to develop ANY new feature...

Fortunately for you, we have [larajobs](https://larajobs.com/) where you can find a more decent place to work :)

**Comment by laurencei** [comment]
If anyone wants to write a detailed guide upgrading 5.1 to 5.5 as a "single" step, they are welcome to submit a PR for Taylor to consider.

**Comment by stevesweets** [comment]
I have to do this on a project, so i'll attempt to write a 5.1 to 5.5 single step guide and do a pull req.

**Comment by michaeldyrynda** [comment]
I wouldn't advise 5.1 -> 5.5 in one big step. If you look at each of the individual upgrade guides, you'll see there's quite a bit involved, particularly 5.2 - 5.3 and 5.3 - 5.4. It's a more sane approach to do each individually and ensure things work between, rather than sweeping changes from 5.1 to 5.5 - bearing in mind not only is the framework version changing, but so is the minimum PHP version.
