### ISSUE TITLE
documentation example on default values with {locale} a bit confusing

### ISSUE THREAD

**Issue by deathkillz** [laravel/docs#3853]
I was implementing the new laravel 5.5 'default value' to make my project use {locale} param in urls like:

mysite.tld/en/section
mysite.tld/nl/section

i followed this:
https://laravel.com/docs/5.5/urls#default-values

there it says:

> You may wish to call this method from a **_route middleware_** so that you have access to the current request

and **_route middleware_** links to:
https://laravel.com/docs/5.5/middleware#assigning-middleware-to-routes

where it says:

> By default, the $routeMiddleware property of this class contains entries for the middleware included with Laravel.
> To add your own, simply append it to this list and assign it a key of your choosing

so when adding it to $routeMiddleware and then adding the middelware to the routes itself initially seems to work very well.

Im using auth scaffolding so to add the middelware to the auth routes i copied them to my web.php routes file and all was still fine.

However,
it does break in one instance and that is when the login session has expired and internally the path to login redirect gets called... or in this case, the path to: {locale}/login

`Illuminate \ Routing \ Exceptions \ UrlGenerationException
Missing required parameters for [Route: login] [URI: {locale}/login].`

after some investigation a better way would be to just add the middelware as first entry in: $middlewareGroups.

---------------------------------------

36864 commented on 25 Sep

Just to clarify, the error occurs because there is a call to route() made in a middleware in the default 'web' group (using laravel's built-in Auth), which is called before any middleware you define in route files.

Possible solutions:
 - Change the docs to clarify that defaults need to be set before any potential call to route();
 - Change the way defaults are handled to ensure any call to route() will find the defaults;
 - Change the order in which middleware is called, so route- or group-specific middleware runs before more general middleware;
 - Make defaults "lazy" or provide a static fallback value for defaults so a call to route() before the defaults are set doesn't cause an exception. Lazy loading defaults would probably imply finishing the middleware stack execution even if a redirect is triggered, which might not be desirable.
--

see also:
https://github.com/laravel/internals/issues/810

**Comment by laurencei** [comment]
@themsaid - thoughts? Do you think we need to highlight the use of middleware in a certain order, or leave it as is?

**Comment by laurencei** [comment]
I've been giving this some thought. The reality is it is up to each application how to handle it - there is no single solution. For example:

> the login session has expired and internally the path to login redirect gets called... or in this case, the path to: {locale}/login

If the session has expired - then there is no default available. i.e. you have no `$user` at all. In this single instance you have two options:

1. Have a generic `login` page without any locale
2. Have different `login` pages, and you can add a custom method to guess which locale to use (i.e. based upon IP).

Meanwhile, the idea to place the default locale into the global middleware before the auth doesnt solve the problem either, because then you dont have access to the `$user` used in the example (since no auth has occured).

I dont see any easy way for this to be placed into the docs. It is really a custom solution, and there is no one right answer.

If anyone has a good idea how this *could* be placed in the docs, you are welcome to make a PR with the idea and we can review that.
