### ISSUE TITLE
Installation of previous versions of the Framework

### ISSUE THREAD

**Issue by temporaryaccount** [laravel/docs#4037]
Suppose I want to install the LTS version of Laravel Framework. If I open the [Installation](https://laravel.com/docs/5.5#installation) section of the 5.5 version's documentation and follow the instructions I will have the latest version installed instead of LTS.

I suggest we change all the versions of the documentation so that when following the installation instructions we end up with the same version of the framework as the documentation.

**Comment by browner12** [comment]
I'm assuming you're referring to the Laravel Installer, since using `composer create` you can specify the version you'd like.

It looks like the installer is only capable of installing either 'master' or 'develop' branch of `laravel/laravel`.  In order to allow the installer to install a selected version we would need to both update the `NewCommand`, and have Taylor zip up the versions in http://cabinet.laravel.com.

So this isn't as simple as a doc change right now, would need to change functionality first.

**Comment by temporaryaccount** [comment]
Well then we could at least specify the version for "composer create" command for every branch of the documentation. It seems @aejnsn has already started doing that by abd516eec1a6fd19e6cd55a5a27a591a9f580ed8 commit today, but I think we should do this for all the branches.

**Comment by laurencei** [comment]
I'm closing this ticket. I submitted a PR for this, although Taylor has decided to leave it as is.
