### ISSUE TITLE
Database transactions removed from laravel database testing

### ISSUE THREAD

**Issue by TheSachin** [laravel/docs#4110]
I just noticed that documentation for trait 
`Illuminate\Foundation\Testing\DatabaseTransactions` has been removed. Is there reason? Is this Trait going to be depreciated?

**Comment by laurencei** [comment]
There is no formal announcement of a deprciation.

The recommendation for Laravel 5.6 is simply to use the `RefreshDatabase` trait, which uses transacitons under the hood.

**Comment by gr33k01** [comment]
I feel like I'm missing something here. Came here wondering the same thing @TheSachin was wondering. The testing docs don't say anything about using transactions under the hood and it's kinda confusing / ambiguous what it means by `reset database` when the docs say `It is often useful to reset your database after each test so that data from a previous test does not interfere with subsequent tests.` 

Does `reset` mean roll the DB back to the state before the tests are run or does this mean essentially a fresh migration of your database?

When I use the `RefreshDatabase` trait on my tests, all my data gets dropped, but when I use the `DatabaseTransactions` trait, my test data isn't persisted but my other data isn't dropped. 

@laurencei Can you point me in the right direction here? Am I missing some sort of test configuration or testing setup?

**Comment by gr33k01** [comment]
If the best practice is to configure a separate test database for factory data or to run tests against a database without any persisted data, I think it'd be helpful to point this out in the database testing docs.

**Comment by michaeldyrynda** [comment]
> The `RefreshDatabase` trait takes the most optimal approach

I don't think the docs necessarily need to explain _how_ this happens, if you're curious, you can dive into the source and see for yourself. The docs broadly explain what is happening, but I don't believe it's their place to explain the inner workings.

Using `DatabaseTransactions` will run individual tests inside a transaction, so  everything within that test is rolled back at the end of the test.

With `RefreshDatabase`, it will essentially run the `migrate:fresh` Artisan command; that is, it will drop the entire database and run your migrations before each test, unless you are using an in-memory SQLite database, where it simply runs `migrate` (the database does not persist between tests in memory).

This is a means of "world building" and ensuring that each test starts in the exact same state.

**Comment by TheSachin** [comment]
Problem with that is, 

- It takes more time rather than DatabaseTransactions

- Doesn't allow complicated setups. My setup is basically before whole suite is ran against. I want to have certain models in db and just before test is executed i want it to be reset again.
Then again my way of doing could be wrong.

**Comment by enriqg9** [comment]
@TheSachin Another problem is that the database seeds are not run, so if your application depends on some seeds this will not work as every time the database is wiped and does not get seeded.
