### ISSUE TITLE
Eloquent Static Examples

### ISSUE THREAD

**Issue by jonathangoncalves** [laravel/docs#4222]
Hi Guys,

Lately i've reading the Eloquent docs and saw that the examples are made calling its functions statically, but when I put this on my code, apparently was wrong. 
https://laravel.com/docs/5.6/eloquent#retrieving-single-models

### Simple Example:

```php
$flights = App\Flight::find([1, 2, 3]);
```

But in the file that declares the "find" function is that way:

   ```php
 /**
     * Execute a query for a single record by ID.
     *
     * @param  int    $id
     * @param  array  $columns
     * @return mixed|static
     */
    public function find($id, $columns = ['*'])
    {
        return $this->where('id', '=', $id)->first($columns);
    }
```

So the example is wrong right?  I can't call statically a function that isn't declared as Static.
Consulting the PHP standards, I can call that function in two ways:

```php
$FlightModel = new App\Flight;
$flight = $FlightModel->find(1);
```

or

```php
$flight = (new App\Flight)->find(1);
```

What should I do?
The docs will be updated?

**Comment by enderandpeter** [comment]
Did you get an error when you ran `App\Flight::find([1, 2, 3])`? If I'm not mistaken, the base model class is using magic methods to call the corresponding instance methods.

**Comment by jhoff** [comment]
Your first issue is that the `find` method doesn't accept an array. You want `whereIn`.

```
$flights = App\Flight::whereIn('id', [1, 2, 3])->get();
```

Secondly, as @enderandpeter eluded to, the find method isn't part of the model class. It's part of the query builder class. When a static method is called on a method that it can't handle, it'll call that unhandled method on a new query builder instance.

**Comment by jonathangoncalves** [comment]
Not an error, but according [PHP.net  documentation](http://php.net/manual/en/language.oop5.static.php):

> In PHP 7, calling non-static methods statically is deprecated, and will generate an E_DEPRECATED warning. Support for calling non-static methods statically may be removed in the future.

So it's better to use the right way for a better compatibility in the future, since that support will be removed in the future, right?

**Comment by enderandpeter** [comment]
The static method `App\Flight::find` is indeed being called statically. The model classes are using [magic methods](http://www.php.net/manual/en/language.oop5.magic.php) to call a method of the same name on an instance of the class. Magic methods allow you to define what happens when you look up a name that does not exist on a class or object. So, when PHP sees that there is no static `find` method on the class, it calls the `__callStatic` method on the class, which is creating an instance of the model and calling the `find` method on that instance and returning the result.

**Comment by jonathangoncalves** [comment]
So that warning on PHP.net documentation should be ignored?

**Comment by enderandpeter** [comment]
Absolutely not, sir. The framework is adhering to that policy. Again, the `find` method is most certainly being called statically on the model class. It is just that instead of a `find` method being defined directly on the model class, somewhere up the inheritance chain there is a `__callStatic` method that is calling such methods on an instance of the class.

**Comment by laurencei** [comment]
This does not appear to be a documentation issue. If there is a specific issue with the docs please let me know. Otherwise I'll close this for now.
