### ISSUE TITLE
Missing breaking change guide on the L5.7 upgrade page (decimal cast)

### ISSUE THREAD

**Issue by markovic-nikola** [laravel/docs#4775]
Hi,
When trying to upgrade from `5.6` to `5.7` I experienced a breaking change.
In the models wherever I defined attributes as `decimal` error occurred.

So in the upgrade guide it should state that decimal type casts must have number of decimals defined.
Example:
```php
// OLD
protected $casts = [
    'score' => 'decimal',
];

// NEW
protected $casts = [
    'score' => 'decimal:2',
];
```
I wasn't sure how would you like to write the description, so I'll just submit this issue.

**Comment by driesvints** [comment]
Decimal was only added in 5.7 later and wasn't available in 5.6: https://github.com/laravel/framework/pull/26173

**Comment by markovic-nikola** [comment]
@driesvints 
I know that, that's why it's breaking now.
Did you read my comment entirely? I said I upgraded from 5.6 to 5.7.

**Comment by driesvints** [comment]
I think you misunderstand the meaning of "breaking". Breaking would meant that existing functionality has changed in a way that requires changes by the user and that should indeed be in the upgrade guide. But new functionality which wasn't there before isn't breaking it just adds to the possibilities what you can do with the framework. We can't possible add every single new thing to the upgrade guide because we can't predict what others may or may not have already implemented themselves.

**Comment by markovic-nikola** [comment]
Eloquent's attribute casting is already an existing functonality...
And in 5.7 decimal casting was changed (not a new functionality) in a way that will affect all instances ( when upgrading) where decimal is used for casting. 
And as I know upgrade guide is there to avoid such situations, not to mention there are cases pointed out on the page that are less likely to happen than this one.

I honestly think that you are wrong with this decision, but not going to continue with the debate.
Thanks for your time anyway...

**Comment by michaeldyrynda** [comment]
@markovic-nikola I think the point @driesvints was trying to get across was that it's not a break as it _is_ new functionality.

If you compare the `castAttribute` method between [5.6](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L468) and [5.7](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L468), you'll see it's a new - not changed - feature.

I suspect that if it's broken since upgrading to 5.7, you had added the functionality into your app in 5.6 in some other manner.
